// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// epmnp
List epmnp(NumericVector mu, NumericMatrix Sigma, int choice_index);
RcppExport SEXP _fsprobit_epmnp(SEXP muSEXP, SEXP SigmaSEXP, SEXP choice_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type choice_index(choice_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(epmnp(mu, Sigma, choice_index));
    return rcpp_result_gen;
END_RCPP
}
// hmcmnp
List hmcmnp(NumericVector mu, NumericMatrix Precision, int choice_index, int n_mc);
RcppExport SEXP _fsprobit_hmcmnp(SEXP muSEXP, SEXP PrecisionSEXP, SEXP choice_indexSEXP, SEXP n_mcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Precision(PrecisionSEXP);
    Rcpp::traits::input_parameter< int >::type choice_index(choice_indexSEXP);
    Rcpp::traits::input_parameter< int >::type n_mc(n_mcSEXP);
    rcpp_result_gen = Rcpp::wrap(hmcmnp(mu, Precision, choice_index, n_mc));
    return rcpp_result_gen;
END_RCPP
}
// metmnp
List metmnp(NumericVector mu, NumericMatrix Sigma, int choice_index, int n_mc);
RcppExport SEXP _fsprobit_metmnp(SEXP muSEXP, SEXP SigmaSEXP, SEXP choice_indexSEXP, SEXP n_mcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type choice_index(choice_indexSEXP);
    Rcpp::traits::input_parameter< int >::type n_mc(n_mcSEXP);
    rcpp_result_gen = Rcpp::wrap(metmnp(mu, Sigma, choice_index, n_mc));
    return rcpp_result_gen;
END_RCPP
}
// mnp_probit_accumulate_cpp
List mnp_probit_accumulate_cpp(NumericVector X, IntegerVector Y, IntegerVector obs_set, NumericMatrix beta, NumericMatrix Sigma, NumericMatrix Precision, std::string E_method, int n_mc);
RcppExport SEXP _fsprobit_mnp_probit_accumulate_cpp(SEXP XSEXP, SEXP YSEXP, SEXP obs_setSEXP, SEXP betaSEXP, SEXP SigmaSEXP, SEXP PrecisionSEXP, SEXP E_methodSEXP, SEXP n_mcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type obs_set(obs_setSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Precision(PrecisionSEXP);
    Rcpp::traits::input_parameter< std::string >::type E_method(E_methodSEXP);
    Rcpp::traits::input_parameter< int >::type n_mc(n_mcSEXP);
    rcpp_result_gen = Rcpp::wrap(mnp_probit_accumulate_cpp(X, Y, obs_set, beta, Sigma, Precision, E_method, n_mc));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fsprobit_epmnp", (DL_FUNC) &_fsprobit_epmnp, 3},
    {"_fsprobit_hmcmnp", (DL_FUNC) &_fsprobit_hmcmnp, 4},
    {"_fsprobit_metmnp", (DL_FUNC) &_fsprobit_metmnp, 4},
    {"_fsprobit_mnp_probit_accumulate_cpp", (DL_FUNC) &_fsprobit_mnp_probit_accumulate_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_fsprobit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
