# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sparse EP moment approximation for multinomial probit
#'
#' @param mu Mean vector of the latent utilities.
#' @param Sigma Covariance matrix of the latent utilities.
#' @param choice_index Choice index: 0 for the base choice, otherwise 1..m for
#'   the selected non-base latent utility.
#' @return A list with approximate truncated-normal `mu` and `Sigma`.
epmnp <- function(mu, Sigma, choice_index) {
    .Call(`_fsprobit_epmnp`, mu, Sigma, choice_index)
}

rcpp_hello <- function() {
    .Call(`_fsprobit_rcpp_hello`)
}

