# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sparse EP moment approximation for multinomial probit
#'
#' @param mu Mean vector of the latent utilities.
#' @param Sigma Covariance matrix of the latent utilities.
#' @param choice_index Choice index: 0 for the base choice, otherwise 1..m for
#'   the selected non-base latent utility.
#' @return A list with approximate truncated-normal `mu` and `Sigma`.
epmnp <- function(mu, Sigma, choice_index) {
    .Call(`_fsprobit_epmnp`, mu, Sigma, choice_index)
}

#' Exact HMC moments for reference-identified multinomial probit
#'
#' @param mu Mean vector of the relative latent utilities.
#' @param Precision Precision matrix of the relative latent utilities.
#' @param choice_index Choice index: 0 for the base choice, otherwise 1..m.
#' @param n_mc Number of retained Monte Carlo samples after 30 burn-in draws.
#' @return A list containing Monte Carlo estimates `mu` and `Sigma`.
hmcmnp <- function(mu, Precision, choice_index, n_mc) {
    .Call(`_fsprobit_hmcmnp`, mu, Precision, choice_index, n_mc)
}

#' Accumulate E-step sufficient statistics for multinomial probit
#'
#' @param X \eqn{n \times m \times p} covariate array.
#' @param Y Integer response codes with base choice coded as 1.
#' @param obs_set One-based observation indices to include.
#' @param beta Current or effective coefficient matrix.
#' @param Sigma Current or effective latent utility covariance.
#' @param Precision Current latent utility precision.
#' @param E_method E-step moment method: `"EPMNP"` or `"HMC"`.
#' @param n_mc Number of retained Monte Carlo samples for HMC.
#' @return A list of accumulated M-step sufficient statistics.
mnp_probit_accumulate_cpp <- function(X, Y, obs_set, beta, Sigma, Precision, E_method, n_mc) {
    .Call(`_fsprobit_mnp_probit_accumulate_cpp`, X, Y, obs_set, beta, Sigma, Precision, E_method, n_mc)
}

